#############################################################################
# Makefile for building: chapi_project
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  chapi_project.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile chapi_project.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-common \
		sub-chapi \
		sub-blink


sub-common-qmake_all:  FORCE
	@test -d common/ || mkdir -p common/
	cd common/ && $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/common/common.pro -o Makefile
	cd common/ && $(MAKE) -f Makefile qmake_all
sub-common: FORCE
	@test -d common/ || mkdir -p common/
	cd common/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/common/common.pro -o Makefile ) && $(MAKE) -f Makefile
sub-common-make_first: FORCE
	@test -d common/ || mkdir -p common/
	cd common/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/common/common.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-common-all: FORCE
	@test -d common/ || mkdir -p common/
	cd common/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/common/common.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-common-clean: FORCE
	@test -d common/ || mkdir -p common/
	cd common/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/common/common.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-common-distclean: FORCE
	@test -d common/ || mkdir -p common/
	cd common/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/common/common.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-common-install_subtargets: FORCE
	@test -d common/ || mkdir -p common/
	cd common/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/common/common.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-common-uninstall_subtargets: FORCE
	@test -d common/ || mkdir -p common/
	cd common/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/common/common.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-chapi-qmake_all: sub-common-qmake_all FORCE
	@test -d chapi/ || mkdir -p chapi/
	cd chapi/ && $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/chapi/chapi.pro -o Makefile
	cd chapi/ && $(MAKE) -f Makefile qmake_all
sub-chapi: sub-common FORCE
	@test -d chapi/ || mkdir -p chapi/
	cd chapi/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/chapi/chapi.pro -o Makefile ) && $(MAKE) -f Makefile
sub-chapi-make_first: sub-common-make_first FORCE
	@test -d chapi/ || mkdir -p chapi/
	cd chapi/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/chapi/chapi.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-chapi-all: sub-common-all FORCE
	@test -d chapi/ || mkdir -p chapi/
	cd chapi/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/chapi/chapi.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-chapi-clean: sub-common-clean FORCE
	@test -d chapi/ || mkdir -p chapi/
	cd chapi/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/chapi/chapi.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-chapi-distclean: sub-common-distclean FORCE
	@test -d chapi/ || mkdir -p chapi/
	cd chapi/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/chapi/chapi.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-chapi-install_subtargets: sub-common-install_subtargets FORCE
	@test -d chapi/ || mkdir -p chapi/
	cd chapi/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/chapi/chapi.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-chapi-uninstall_subtargets: sub-common-uninstall_subtargets FORCE
	@test -d chapi/ || mkdir -p chapi/
	cd chapi/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/chapi/chapi.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-blink-qmake_all: sub-common-qmake_all FORCE
	@test -d blink/ || mkdir -p blink/
	cd blink/ && $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/blink/blink.pro -o Makefile
	cd blink/ && $(MAKE) -f Makefile qmake_all
sub-blink: sub-common FORCE
	@test -d blink/ || mkdir -p blink/
	cd blink/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/blink/blink.pro -o Makefile ) && $(MAKE) -f Makefile
sub-blink-make_first: sub-common-make_first FORCE
	@test -d blink/ || mkdir -p blink/
	cd blink/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/blink/blink.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-blink-all: sub-common-all FORCE
	@test -d blink/ || mkdir -p blink/
	cd blink/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/blink/blink.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-blink-clean: sub-common-clean FORCE
	@test -d blink/ || mkdir -p blink/
	cd blink/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/blink/blink.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-blink-distclean: sub-common-distclean FORCE
	@test -d blink/ || mkdir -p blink/
	cd blink/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/blink/blink.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-blink-install_subtargets: sub-common-install_subtargets FORCE
	@test -d blink/ || mkdir -p blink/
	cd blink/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/blink/blink.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-blink-uninstall_subtargets: sub-common-uninstall_subtargets FORCE
	@test -d blink/ || mkdir -p blink/
	cd blink/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/blink/blink.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: chapi_project.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		chapi_project.pro
	$(QMAKE) -o Makefile chapi_project.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
chapi_project.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile chapi_project.pro

qmake_all: sub-common-qmake_all sub-chapi-qmake_all sub-blink-qmake_all FORCE

make_first: sub-common-make_first sub-chapi-make_first sub-blink-make_first FORCE
all: sub-common-all sub-chapi-all sub-blink-all FORCE
clean: sub-common-clean sub-chapi-clean sub-blink-clean FORCE
distclean: sub-common-distclean sub-chapi-distclean sub-blink-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-common-install_subtargets sub-chapi-install_subtargets sub-blink-install_subtargets FORCE
uninstall_subtargets: sub-common-uninstall_subtargets sub-chapi-uninstall_subtargets sub-blink-uninstall_subtargets FORCE

sub-common-check:
	@test -d common/ || mkdir -p common/
	cd common/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/common/common.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-chapi-check: sub-common-check
	@test -d chapi/ || mkdir -p chapi/
	cd chapi/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/chapi/chapi.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-blink-check: sub-common-check
	@test -d blink/ || mkdir -p blink/
	cd blink/ && ( test -e Makefile || $(QMAKE) /home/samuel/dev_perso/chapi_client_sshfs/blink/blink.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-common-check sub-chapi-check sub-blink-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

