#############################################################################
# Makefile for building: chapi_project
# Generated by qmake (2.01a) (Qt 4.8.6) on: sam. avr. 18 19:09:44 2015
# Project:  chapi_project.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -o Makefile chapi_project.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-common \
		sub-chapi \
		sub-blink

common//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) common/ || $(MKDIR) common/ 
	cd common/ && $(QMAKE) /home/samuel/dev_perso/chapi_client/common/common.pro -o $(MAKEFILE)
sub-common-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) common/ || $(MKDIR) common/ 
	cd common/ && $(QMAKE) /home/samuel/dev_perso/chapi_client/common/common.pro -o $(MAKEFILE)
sub-common: common//$(MAKEFILE) FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE)
sub-common-make_default: common//$(MAKEFILE) FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE) 
sub-common-make_first: common//$(MAKEFILE) FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE) first
sub-common-all: common//$(MAKEFILE) FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE) all
sub-common-clean: common//$(MAKEFILE) FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE) clean
sub-common-distclean: common//$(MAKEFILE) FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE) distclean
sub-common-install_subtargets: common//$(MAKEFILE) FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE) install
sub-common-uninstall_subtargets: common//$(MAKEFILE) FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE) uninstall
chapi//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) chapi/ || $(MKDIR) chapi/ 
	cd chapi/ && $(QMAKE) /home/samuel/dev_perso/chapi_client/chapi/chapi.pro -o $(MAKEFILE)
sub-chapi-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) chapi/ || $(MKDIR) chapi/ 
	cd chapi/ && $(QMAKE) /home/samuel/dev_perso/chapi_client/chapi/chapi.pro -o $(MAKEFILE)
sub-chapi: chapi//$(MAKEFILE) sub-common FORCE
	cd chapi/ && $(MAKE) -f $(MAKEFILE)
sub-chapi-make_default: chapi//$(MAKEFILE) sub-common-make_default FORCE
	cd chapi/ && $(MAKE) -f $(MAKEFILE) 
sub-chapi-make_first: chapi//$(MAKEFILE) sub-common-make_first FORCE
	cd chapi/ && $(MAKE) -f $(MAKEFILE) first
sub-chapi-all: chapi//$(MAKEFILE) sub-common-all FORCE
	cd chapi/ && $(MAKE) -f $(MAKEFILE) all
sub-chapi-clean: chapi//$(MAKEFILE) sub-common-clean FORCE
	cd chapi/ && $(MAKE) -f $(MAKEFILE) clean
sub-chapi-distclean: chapi//$(MAKEFILE) sub-common-distclean FORCE
	cd chapi/ && $(MAKE) -f $(MAKEFILE) distclean
sub-chapi-install_subtargets: chapi//$(MAKEFILE) sub-common-install_subtargets FORCE
	cd chapi/ && $(MAKE) -f $(MAKEFILE) install
sub-chapi-uninstall_subtargets: chapi//$(MAKEFILE) sub-common-uninstall_subtargets FORCE
	cd chapi/ && $(MAKE) -f $(MAKEFILE) uninstall
blink//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) blink/ || $(MKDIR) blink/ 
	cd blink/ && $(QMAKE) /home/samuel/dev_perso/chapi_client/blink/blink.pro -o $(MAKEFILE)
sub-blink-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) blink/ || $(MKDIR) blink/ 
	cd blink/ && $(QMAKE) /home/samuel/dev_perso/chapi_client/blink/blink.pro -o $(MAKEFILE)
sub-blink: blink//$(MAKEFILE) sub-common FORCE
	cd blink/ && $(MAKE) -f $(MAKEFILE)
sub-blink-make_default: blink//$(MAKEFILE) sub-common-make_default FORCE
	cd blink/ && $(MAKE) -f $(MAKEFILE) 
sub-blink-make_first: blink//$(MAKEFILE) sub-common-make_first FORCE
	cd blink/ && $(MAKE) -f $(MAKEFILE) first
sub-blink-all: blink//$(MAKEFILE) sub-common-all FORCE
	cd blink/ && $(MAKE) -f $(MAKEFILE) all
sub-blink-clean: blink//$(MAKEFILE) sub-common-clean FORCE
	cd blink/ && $(MAKE) -f $(MAKEFILE) clean
sub-blink-distclean: blink//$(MAKEFILE) sub-common-distclean FORCE
	cd blink/ && $(MAKE) -f $(MAKEFILE) distclean
sub-blink-install_subtargets: blink//$(MAKEFILE) sub-common-install_subtargets FORCE
	cd blink/ && $(MAKE) -f $(MAKEFILE) install
sub-blink-uninstall_subtargets: blink//$(MAKEFILE) sub-common-uninstall_subtargets FORCE
	cd blink/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: chapi_project.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile chapi_project.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile chapi_project.pro

qmake_all: sub-common-qmake_all sub-chapi-qmake_all sub-blink-qmake_all FORCE

make_default: sub-common-make_default sub-chapi-make_default sub-blink-make_default FORCE
make_first: sub-common-make_first sub-chapi-make_first sub-blink-make_first FORCE
all: sub-common-all sub-chapi-all sub-blink-all FORCE
clean: sub-common-clean sub-chapi-clean sub-blink-clean FORCE
distclean: sub-common-distclean sub-chapi-distclean sub-blink-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-common-install_subtargets sub-chapi-install_subtargets sub-blink-install_subtargets FORCE
uninstall_subtargets: sub-common-uninstall_subtargets sub-chapi-uninstall_subtargets sub-blink-uninstall_subtargets FORCE

sub-common-check: common/$(MAKEFILE)
	cd common/ && $(MAKE) -f $(MAKEFILE) check
sub-chapi-check: chapi/$(MAKEFILE) sub-common-check
	cd chapi/ && $(MAKE) -f $(MAKEFILE) check
sub-blink-check: blink/$(MAKEFILE) sub-common-check
	cd blink/ && $(MAKE) -f $(MAKEFILE) check
check: sub-common-check sub-chapi-check sub-blink-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

